# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-01 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isbn13', models.CharField(max_length=13)),
                ('title', models.TextField()),
                ('status', models.CharField(choices=[('0', '\u8fd4\u5374'), ('1', '\u8cb8\u51fa')], default='0', max_length=1)),
                ('smallThumbnail', models.TextField()),
                ('Thumbnail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('tnet_id', models.CharField(max_length=7)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='retntalUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookrental.User'),
        ),
    ]
